<a href="https://colab.research.google.com/github/methrex/COT5600/blob/master/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import scipy.linalg as la


In [0]:
def vec(A):
    #Vectorizes a matrix A, column by column
    v=[]
    N=A.shape[0]
    for i in range(N):
        for k in range(N):
            v.append(A[k][i])
    return v


In [0]:
def annihilate_poly(M,n):
    #takes as input a square matrix M of size N x N
    #
    #returns an array whose elements are the coefficients of a polynomial of
    #degree n that annihilates the matrix M. There may be multiple vectors in
    #the null space of the matrix, such as for the identity matrix, so we will
    #just choose the first one. 
    #
    #This is not necessarily the minimal polynomial of M! There may also not
    #exist a polynomial of this degree that annihilates M.
    
    N=M.shape[0]
        
    A=[]
    for k in range(n+1):
        if k==0:
            I=np.identity(N)
            A.append(vec(I))
        else:
            A.append(vec(M**(k)))
            
    A=np.transpose(A)
            
    NA=la.null_space(np.asmatrix(A))    #cols of NA should send A to 0
    return NA

def annihilate_min_deg_poly(M):
    #takes as input an N x N matrix M and iteratively finds the minimal
    #polynomial
        
    #check if zero-matrix
        
    #M^1, then M^1 and M^2, then ..... use above function^
    N=M.shape[0]
        
    if np.all(M-np.identity(N) ==0):
        print('You supplied the identity. Minimal polynomial is:')
        print('I-I=0')
        return[1,-1]
    elif np.all(M==0):
        print('You supplied the 0 matrix')
        return []
        
    for i in range(1,N+1):
    
        c=annihilate_poly(M,i)
        if c.size == 0:
          continue
        elif c.shape[1]==1:
          c=c/(np.linalg.norm(c,ord=2))
          print('Minimal polynomial found!');print('');
          print('Degree: ',str(i))
          return c
        else:
          print("There's a problem")

    
        

In [49]:
 #run this cell!
 M=np.array([[2,0,0],[0,2,0],[0,1,3]])   #initialize some square numpy matrix

coefs = annihilate_min_deg_poly(M)       #coefficients of minimal polynomial
print('Coefficients of the minimal polynomial are:');print('')
print(coefs);print('')

#test that it works
for i in range(M.shape[0]+1):
  if i==0:
    sum=coefs[i]*np.identity(M.shape[0])
  else:
    sum = sum + coefs[i]*M**i
print('The following should be pretty close to the zero matrix');print('')
print(sum)



Minimal polynomial found!

Degree:  3
Coefficients of the minimal polynomial are:

[[-0.46017899]
 [-0.53687549]
 [ 0.69026849]
 [-0.153393  ]]

The following should be pretty close to the zero matrix

[[-4.44089210e-16  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -4.44089210e-16  0.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16  0.00000000e+00]]
