<a href="https://colab.research.google.com/github/methrex/COT5600/blob/master/hw_4/COT5600_HW4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

Problem 1
---

I pulled Floyd's cycle detection from

https://en.wikipedia.org/wiki/Cycle_detection

and defined a function to test. This function adds 1 to an integer and wraps back around to 0 when we hit the order of the group.

In [0]:
def f_add(x,N):
  # -- example function
  # -- 0, 1, 2, ..., N
  return x+1 % (N+1)
# -- end function f_add --------------------------------------------------------

def floyd(f,x0):
  slow = f(x0)
  fast = f(f(x0))

  while slow != fast:
    slow =   f(slow)
    fast = f(f(fast))

  pos  = 0
  slow = x0
  while slow != fast:
    slow  = f(slow)
    fase  = f(fast)
    pos  += 1

  len = 1
  fast = f(slow)
  while slow != fast:
    fast = f(fast)
    len += 1

  return len, pos
# -- end function floyd --------------------------------------------------------

Problem 2 (and a continuation of Problem 1)
---

Now, we want to find the order of some integer $a^r \equiv 1\mod{N}$

In [0]:
def find_order(a,N):
  
  def f_raise(x):
    nonlocal a
    return x*a % N+1
  
  _,r = floyd(f_raise,a)

  return r

Let's see if this works!

$$ 5^3 = 125  $$

$$ 4^3 = 64   $$

$$ 5^5 = 3125 $$

In [4]:
print('Order: r =',find_order(5,125))
print('Order: r =',find_order(4,64))
print('Order: r =',find_order(5,3125))

Order: r = 3
Order: r = 3
Order: r = 5


In [5]:
# -- use your own 'a' and 'N'
a = 13   # <-------------------------- [change this!]
r = 9    # <-------------------------- [change this too!]
N = a**r
print('Order: r =',find_order(a,N))

Order: r = 9


Problem 3
---

Factor an integer $N$

In [0]:
def fact(N):
  fact = 1
  for k in range(2,N+1):
    fact *= k
  return int(fact)

def factor(N):
  step = 0
  while True:
    
    if step > 10000:
      print('No nontrivial factor in '+str(step)+' steps. Quitting')
      return -1
    step += 1

    # -- choose a randomly from {2,...,N-1}
    a = np.random.randint(2,N)

    # -- find the order of a^r 
    r = int(find_order(a,N))
    if r==0:
      continue

    # -- get factor if r is even and not a trivial factor
    if not r%2  and r!= N:

      f = np.gcd(int(a**int(r/2-1)),int(N))
      if f==1:
        continue
      else:
        return f
        print(hi)


Does it work? Let's look at the number
$$
8!= 40320
$$
By definition, its nontrivial factors are
$$
2,3,4,5,6,\text{ and }7
$$

as well as some of their multiples.

In [7]:
factors=[]
N = fact(8)  
for k in range(100):
  factors.append(factor(N))

factors.sort()

# -- sorted and reshaped array of the factors of 8! for 
#    100 tries
print(np.reshape(factors,(10,10)))

[[   5    5    5    7    7    7    7    8    8    8]
 [   8    8    8    8    8    8    9    9    9    9]
 [   9    9    9    9    9    9    9    9    9    9]
 [   9    9    9    9    9    9   12   15   16   16]
 [  20   21   24   24   28   32   32   35   36   40]
 [  45   45   45   45   63   63   64   64   72   72]
 [  80  128  128  128  128  128  128  128  128  128]
 [ 128  128  128  128  128  128  128  128  144  144]
 [ 144  160  160  160  280  288  288  315  504  640]
 [ 720  896  896  896  896  896  896  896 1152 1152]]


Larger numbers will not work for the code I've written. I think I need to handle them a bit differently. I occasionally had trouble when handling 10!, for example.