<a href="https://colab.research.google.com/github/methrex/COT5600/blob/master/hw_1/_hw_1_problem_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Homework assignment 1, problem 2 ::: Josh Forer

In [0]:
#imports
import numpy as np
import scipy.linalg as la


In [0]:
#==================== DEFINITIONS ==============================================
def norm(A,n=2):
  return np.linalg.norm(A,ord=n)
#end function norm
#-------------------------------------------------------------------------------

def vec(A):                                                                    
  #Vectorizes a matrix A, column by column                                     
                                                                               
  v=[]                                                                         
  N=A.shape[0]                                                                 
  for i in range(N):   
    for k in range(N):
      v.append(A[k][i])
  return v

#end function vec
#-------------------------------------------------------------------------------

def vecsym(A):
  #Vectorizes a symmetric matrix A's upper triangle, column by column

  v=[]
  N=A.shape[0]
  for i in range(N):
    for j in range(i+1):
      v.append(A[j][i])
  return v

#end function vecsym
#------------------------------------------------------------------------------

def annihilate_poly(M,d):
  #takes as input a square matrix M of size N x N
  #
  #returns an array whose elements are the coefficients of a polynomial of
  #degree d that annihilates the matrix M. The null space will be
  #one-dimensional if the polynomial of this degree is the minimal polynomial
    
  N=M.shape[0]
      
  A=[]
  I=np.identity(N)
  symmetry=np.all(M-np.transpose(M))

  if symmetry:
    for k in range(d+1):
      A.append(vecsym(np.linalg.matrix_power(M,d)))
  else:
    for k in range(d+1):
      A.append(vec(np.linalg.matrix_power(M,k)))

  A=np.transpose(A)
  NA=la.null_space(A)    #cols of NA should send A to 0
  return NA

#end function annihilate_poly
#-------------------------------------------------------------------------------

def annihilate_min_deg_poly(M):
  #takes as input an N x N matrix M and iteratively finds the minimal polynomial

  N=M.shape[0]
        
  if np.all(M-np.identity(N) ==0):
      print('You supplied the identity. Minimal polynomial is:')
      print('I-I=0')
      return[1,-1]
  elif np.all(M==0):
      print('You supplied the 0 matrix')
      return []
        
  for i in range(N+1):
      c=annihilate_poly(M,i)
      if c.size == 0:
        continue
      elif c.shape[1]==1:
        c=c/c[-1]    #normalize to make leading coef 1
        print('Minimal polynomial found!',end='\n\n')
        return c
      else:
        print("There's a problem")

#end function annihilate_min_deg_poly
#-------------------------------------------------------------------------------   
        

The following cell tests the code for a matrix in Jordan canonical form.

In [62]:
#-------------------------------------------------------------------------------

#initialize matrix
M=np.array([[2,1,0],[0,2,1],[0,0,2]])    
N=M.shape[0]
K=norm(M)*norm(np.linalg.inv(M))     #condition number of M
 
#find the min poly to annihilate M and output its coefficients
coefs = annihilate_min_deg_poly(M)      

#print the results, but only if there's not too much stuff going on
if N <= 6:                                
  print('The supplied Matrix with condition number '+str(K),end='\n\n');
  print(M,end='\n\n')
  print('Coefficients of the minimal polynomial of degree '+str(len(coefs)-1),end='')
  print(' in increasing order are:',end='\n\n')
  print(coefs);print('')

  print('Our minimal polynomial is:',end='\n\n')

  sum=np.zeros(N)
  count=0
  for i in range(N+1):
    if i==len(coefs):
      break
    if N <=10:
      if count>0:
        print('+ ',end='')
      sum = sum + coefs[i]*np.linalg.matrix_power(M,i)
      print(str(coefs[i])+'*M^'+str(i)+' ',end='')
      count = count + 1
      
    
  print('= ');print('');print(sum)

Minimal polynomial found!

The supplied Matrix with condition number 2.0255996355063006

[[2 1 0]
 [0 2 1]
 [0 0 2]]

Coefficients of the minimal polynomial of degree 3 in increasing order are:

[[-8.]
 [12.]
 [-6.]
 [ 1.]]

Our minimal polynomial is:

[-8.]*M^0 + [12.]*M^1 + [-6.]*M^2 + [1.]*M^3 = 

[[-3.55271368e-15  2.66453526e-14  1.68753900e-14]
 [ 0.00000000e+00 -3.55271368e-15  2.66453526e-14]
 [ 0.00000000e+00  0.00000000e+00 -3.55271368e-15]]


The above should produce the polynomial (x-2)^3

This cell below generates an *n x n* matrix full of numpy.random.randint elements on the interval [-max,max]. 

In [65]:
#-------------------------------------------------------------------------------

#set size of matrix and largest value of largest (magnitude) possible entry
N=6
max=10

#initialize the square matrix M with random entries
M=np.array(np.random.randint(low=-max,high=max,size=(N,N)))
K=norm(M)/norm(np.linalg.inv(M))

#or your your own matrix
#M=np.array([]) 


#find the min poly to annihilate M and output its coefficients
coefs = annihilate_min_deg_poly(M)       

#print the results, but only if there's not too much stuff going on
if N <= 6:                               
  print('The supplied Matrix with condition number '+str(K),end='\n\n')
  print(M,end='\n\n')
  print('Coefficients of the minimal polynomial of degree '+str(len(coefs)-1),end='')
  print(' in increasing order are:',end='\n\n')
  print(coefs,end='\n\n')
  print('Our minimal polynomial is:',end='\n\n')

  sum=np.zeros(N)
  count=0
  for i in range(N+1):
    if i==len(coefs):
      break
    if N <=10:
      if count>0:
        print('+ ',end='')
      sum = sum + coefs[i]*np.linalg.matrix_power(M,i)
      print(str(coefs[i])+'*M^'+str(i)+' ',end='')
      count = count + 1

  print('= ');print('');print(sum)



Minimal polynomial found!

The supplied Matrix with condition number 1.8945230473001304

[[ -8  -4   4  -7  -8   1]
 [  9  -2  -8   8  -5  -9]
 [ -3  -2   4   7  -9   2]
 [-10   4  -8  -4  -6  -4]
 [  5   9  -6   1   6   0]
 [ -5   7  -4  -1   7   2]]

Coefficients of the minimal polynomial of degree 6 in increasing order are:

[[-2.1504e+04]
 [ 7.8330e+04]
 [-7.2730e+03]
 [ 2.2690e+03]
 [ 2.7000e+01]
 [ 2.0000e+00]
 [ 1.0000e+00]]

Our minimal polynomial is:

[-21504.00001896]*M^0 + [78329.99999986]*M^1 + [-7273.00000009]*M^2 + [2269.]*M^3 + [27.]*M^4 + [2.]*M^5 + [1.]*M^6 = 

[[-2.98507512e-05  9.94605944e-06 -1.07239466e-05 -5.62262721e-06
  -5.98002225e-06 -2.89839227e-06]
 [ 1.41514465e-05 -1.69980340e-05  1.11348927e-05  1.63223594e-05
   1.67815015e-05  1.11176632e-05]
 [ 1.30296685e-05  2.16421904e-06 -1.89985149e-05  2.42004171e-06
   1.11872796e-05  7.50296749e-07]
 [-1.95959583e-05  4.06964682e-06  4.02552541e-06 -3.11359763e-05
  -1.15344301e-05  6.32705633e-06]
 [-5.088979

Larger matrices, as well as larger max values for randint, produce less accurate results using this method. It works better for smaller matrices (floats or ints).