<a href="https://colab.research.google.com/github/methrex/COT5600/blob/master/hw_1/hw_1_problem_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Homework assignment 1, problem 2 ::: Josh Forer

In [0]:
#imports
import numpy as np
import scipy.linalg as la


In [0]:
#==================== DEFINITIONS ==============================================
def norm(A,n=2):
  return np.linalg.norm(A,ord=n)
#end function norm
#-------------------------------------------------------------------------------

def vec(A):                                                                    
  #Vectorizes a matrix A, column by column                                     
                                                                               
  v=[]                                                                         
  N=A.shape[0]                                                                 
  for i in range(N):   
    for k in range(N):
      v.append(A[k][i])
  return v

#end function vec
#-------------------------------------------------------------------------------

def vecsym(A):
  #Vectorizes a symmetric matrix A's upper triangle, column by column

  v=[]
  N=A.shape[0]
  for i in range(N):
    for j in range(i+1):
      v.append(A[j][i])
  return v

#end function vecsym
#------------------------------------------------------------------------------

def annihilate_poly(M,d):
  #takes as input a square matrix M of size N x N
  #
  #returns an array whose elements are the coefficients of a polynomial of
  #degree d that annihilates the matrix M. The null space will be
  #one-dimensional if the polynomial of this degree is the minimal polynomial
    
  N=M.shape[0]
      
  A=[]
  I=np.identity(N)
  symmetry=np.all(M-np.transpose(M))

  if symmetry:
    for k in range(d+1):
      A.append(vecsym(np.linalg.matrix_power(M,d)))
  else:
    for k in range(d+1):
      A.append(vec(np.linalg.matrix_power(M,k)))

  A=np.transpose(A)
  NA=la.null_space(A)    #cols of NA should send A to 0
  return NA

#end function annihilate_poly
#-------------------------------------------------------------------------------

def annihilate_min_deg_poly(M):
  #takes as input an N x N matrix M and iteratively finds the minimal polynomial

  N=M.shape[0]
        
  if np.all(M-np.identity(N) ==0):
      print('You supplied the identity. Minimal polynomial is:')
      print('I-I=0')
      return[1,-1]
  elif np.all(M==0):
      print('You supplied the 0 matrix')
      return []
        
  for i in range(N+1):
      c=annihilate_poly(M,i)
      if c.size == 0:
        continue
      elif c.shape[1]==1:
        c=c/c[-1]    #normalize to make leading coef 1
        print('Minimal polynomial found!',end='\n\n')
        return c
      else:
        print("There's a problem")

#end function annihilate_min_deg_poly
#-------------------------------------------------------------------------------   
        

The following cell tests the code for a matrix in Jordan canonical form.

In [69]:
#-------------------------------------------------------------------------------

#initialize matrix
M=np.array([[2,1,0],[0,2,1],[0,0,2]])    
N=M.shape[0]
K=norm(M)*norm(np.linalg.inv(M))     #condition number of M
 
#find the min poly to annihilate M and output its coefficients
coefs = annihilate_min_deg_poly(M)      

#print the results, but only if there's not too much stuff going on
if N <= 6:                                
  print('The supplied Matrix with condition number '+str(K),end='\n\n');
  print(M,end='\n\n')
  print('Coefficients of the minimal polynomial of degree '+str(len(coefs)-1),end='')
  print(' in increasing order are:',end='\n\n')
  print(coefs);print('')

  print('Our minimal polynomial is:',end='\n\n')

  sum=np.zeros(N)
  count=0
  for i in range(N+1):
    if i==len(coefs):
      break
    if N <=10:
      if count>0:
        print('+ ',end='')
      sum = sum + coefs[i]*np.linalg.matrix_power(M,i)
      print(str(coefs[i])+'*M^'+str(i)+' ',end='')
      count = count + 1
      
    
  print('= ');print('');print(sum)

Minimal polynomial found!

The supplied Matrix with condition number 2.0255996355063006

[[2 1 0]
 [0 2 1]
 [0 0 2]]

Coefficients of the minimal polynomial of degree 3 in increasing order are:

[[-8.]
 [12.]
 [-6.]
 [ 1.]]

Our minimal polynomial is:

[-8.]*M^0 + [12.]*M^1 + [-6.]*M^2 + [1.]*M^3 = 

[[-3.55271368e-15  2.66453526e-14  1.68753900e-14]
 [ 0.00000000e+00 -3.55271368e-15  2.66453526e-14]
 [ 0.00000000e+00  0.00000000e+00 -3.55271368e-15]]


The above code should produce the polynomial (x-2)^3

This cell below generates an *n x n* matrix full of numpy.random.randint elements on the interval [-max,max]. 

In [70]:
#-------------------------------------------------------------------------------

#set size of matrix and largest value of largest (magnitude) possible entry
N=6
max=10

#initialize the square matrix M with random entries
M=np.array(np.random.randint(low=-max,high=max,size=(N,N)))
K=norm(M)/norm(np.linalg.inv(M))

#or your your own matrix
#M=np.array([]) 


#find the min poly to annihilate M and output its coefficients
coefs = annihilate_min_deg_poly(M)       

#print the results, but only if there's not too much stuff going on
if N <= 6:                               
  print('The supplied Matrix with condition number '+str(K),end='\n\n')
  print(M,end='\n\n')
  print('Coefficients of the minimal polynomial of degree '+str(len(coefs)-1),end='')
  print(' in increasing order are:',end='\n\n')
  print(coefs,end='\n\n')
  print('Our minimal polynomial is:',end='\n\n')

  sum=np.zeros(N)
  count=0
  for i in range(N+1):
    if i==len(coefs):
      break
    if N <=10:
      if count>0:
        print('+ ',end='')
      sum = sum + coefs[i]*np.linalg.matrix_power(M,i)
      print(str(coefs[i])+'*M^'+str(i)+' ',end='')
      count = count + 1

  print('= ');print('');print(sum)



Minimal polynomial found!

The supplied Matrix with condition number 72.44956879328502

[[ -6   1  -4 -10   2 -10]
 [ -5  -3  -4   3   5  -7]
 [  1   9  -4  -5  -8   3]
 [  5 -10 -10  -9   4  -9]
 [  3  -3   1   3   0  -2]
 [ -8  -3  -7 -10 -10   4]]

Coefficients of the minimal polynomial of degree 6 in increasing order are:

[[-1.018616e+06]
 [-3.158220e+05]
 [-1.853500e+04]
 [-1.839000e+03]
 [-2.700000e+01]
 [ 1.800000e+01]
 [ 1.000000e+00]]

Our minimal polynomial is:

[-1018615.99973951]*M^0 + [-315821.9999796]*M^1 + [-18535.00000098]*M^2 + [-1839.00000014]*M^3 + [-27.00000001]*M^4 + [18.]*M^5 + [1.]*M^6 = 

[[-2.01066956e-04  1.57592818e-04  4.24135476e-04  1.72886997e-04
   3.39206308e-05  2.64598057e-04]
 [-4.11172397e-04  2.52066413e-04  1.26557425e-04  2.63251364e-04
  -5.90384007e-05  3.17118131e-04]
 [ 6.51206356e-05  1.85533892e-04 -4.55509871e-05 -3.43669206e-04
  -2.12141313e-04 -1.23767182e-04]
 [-1.43839978e-04 -2.17315974e-04 -2.47266144e-05  1.89436600e-04
  -3.36486

Larger matrices, as well as larger max values for randint, produce less accurate results using this method. It works better for smaller matrices (floats or ints).