<a href="https://colab.research.google.com/github/methrex/COT5600/blob/master/hw_1/hw_1_problem_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import scipy.linalg as la


In [0]:
#==================== DEFINITIONS ==============================================

def vec(A):
  #Vectorizes a matrix A, column by column

  v=[]
  N=A.shape[0]
  for i in range(N):
    for k in range(N):
      v.append(A[k][i])
  return v
#-------------------------------------------------------------------------------

def vecsym(A):
  #Vectorizes a symmetric matrix A's upper triangle, column by column

  v=[]
  N=A.shape[0]
  for i in range(N):
    for j in range(i+1):
      v.append(A[j][i])
  return v
#------------------------------------------------------------------------------

def annihilate_poly(M,n):
  #takes as input a square matrix M of size N x N
  #
  #returns an array whose elements are the coefficients of a polynomial of
  #degree n that annihilates the matrix M. There may be multiple vectors in
  #the null space of the matrix, such as for the identity matrix, so we will
  #just choose the first one. 
  #
  #This is not necessarily the minimal polynomial of M! There may also not
  #exist a polynomial of this degree that annihilates M.
    
  N=M.shape[0]
      
  A=[]
  I=np.identity(N)
  symmetry=np.all(M-np.transpose(M))

  if symmetry:
    for k in range(n+1):
      A.append(vecsym(np.linalg.matrix_power(M,k)))
  else:
    for k in range(n+1):
      A.append(vec(np.linalg.matrix_power(M,k)))

  A=np.transpose(A)
  NA=la.null_space(A)    #cols of NA should send A to 0
  return NA
#-------------------------------------------------------------------------------

def annihilate_min_deg_poly(M):
  #takes as input an N x N matrix M and iteratively finds the minimal polynomial

  N=M.shape[0]
        
  if np.all(M-np.identity(N) ==0):
      print('You supplied the identity. Minimal polynomial is:')
      print('I-I=0')
      return[1,-1]
  elif np.all(M==0):
      print('You supplied the 0 matrix')
      return []
        
  for i in range(N+1):
      c=annihilate_poly(M,i)
      if c.size == 0:
        continue
      elif c.shape[1]==1:
        c=c/c[-1]    #normalize to make leading coef 1
        print('Minimal polynomial found!',end='\n\n')
        return c
      else:
        print("There's a problem")
#-------------------------------------------------------------------------------   
        

In [3]:
#This cell tests the code for a matrix in Jordan canonical form

M=np.array([[2,1,0],[0,2,1],[0,0,2]])    #initialize some square numpy matrix

#-------------------------------------------------------------------------------

N=M.shape[0]
coefs = annihilate_min_deg_poly(M)       #coefficients of minimal polynomial

if N <= 10:                                #don't print too much
  print('The supplied Matrix: ',end='\n\n');print(M,end='\n\n')
  print('Coefficients of the minimal polynomial of degree '+str(len(coefs)-1),end='')
  print(' are:',end='\n\n')
  print(coefs);print('')

#==============   test that it works   =================
print('Our minimal polynomial is:     (x-2)^3');print('')

sum=np.zeros(N)
for i in range(N+1):
  if i==len(coefs):
    break
  if N <=10:
    if i>0:
     print('+ ',end='')
    sum = sum + coefs[i]*np.linalg.matrix_power(M,i)
    print(str(coefs[i])+'*M^'+str(i)+' ',end='')

print('= ');print('');print(sum)



Minimal polynomial found!

The supplied Matrix: 

[[2 1 0]
 [0 2 1]
 [0 0 2]]

Coefficients of the minimal polynomial of degree 3 are:

[[-8.]
 [12.]
 [-6.]
 [ 1.]]

Our minimal polynomial is:     (x-2)^3

[-8.]*M^0 + [12.]*M^1 + [-6.]*M^2 + [1.]*M^3 = 

[[-3.55271368e-15  2.66453526e-14  1.68753900e-14]
 [ 0.00000000e+00 -3.55271368e-15  2.66453526e-14]
 [ 0.00000000e+00  0.00000000e+00 -3.55271368e-15]]
